### ISSUE TITLE
Please update the MIREOT link to not point to http://iospress.metapress.com/content/h54m2237310v13x1/

### ISSUE THREAD

**Issue by rduerr** [jamesaoverton/obo-tutorial#11]
This site is not about MIREOT, so not helpful....  The link is in the section "**Importing Single Terms with MIREOT"**

**Comment by jamesaoverton** [comment]
Thanks for pointing this out. I think I've fixed the problem.

**Comment by joshwhy** [comment]
https://m.wiki.mozilla.org/User:Alexey.gaidukov#/editor/0
