### ISSUE TITLE
Inconsistent IRI creation in annotate and template commands

### ISSUE THREAD

**Issue by spolavar** [jamesaoverton/obo-tutorial#6]
Trying to create owl file from two step process

step#1:
obo to owl conversion:
>java -jar robot.jar annotate --input NCBI_NMOsp_v1.2.obo --ontology-iri "http://neuromorpho.org/neuroMorpho/ontologies/NMOSp.owl" --prefix "NMOSp: http://neuromorpho.org/neuroMorpho/ontologies/NMOSp.owl" --output results/NMOSp.owl

examples of inconsistently created IRIs for different identifiers: 
NMOSp:1000 --> http://purl.obolibrary.org/obo/NMOSp_1000
nif_organism:birnlex_197 --> http://purl.obolibrary.org/obo/nif_organism#_birnlex_197
MESH:D008822 --> http://purl.obolibrary.org/obo/MESH#_D008822
FBal0276838 --> http://purl.obolibrary.org/obo/NCBI_NMOsp_v1.2.obo#FBal0276838

why is the file name NCBI_NMOsp_v1.2.obo used only in the last example? Is it because there is no prefix?
if the IRIs are created by adding '#' to the prefix in the CURIE, then why not prefix 'NMOSp' is used in the same way?

these inconsistencies get more troublesome when merging  the individuals separately to the input owl file, because the IRIs of the same terms are created differently in the two owl files.

step#2:
individuals from template file:
> java -jar robot.jar template --t NMOspindividuals_1.csv --noprefixes --prefix "obo: http://purl.obolibrary.org/obo/" --prefix "NMOSp: http://neuromorpho.org/neuroMorpho/ontologies/NMOSp.owl#" --output results/NMOSp_.owl

FBal0276838 is created as http://purl.obolibrary.org/obo/FBal0276838

Note the difference in IRIs in both cases.

**Comment by jamesaoverton** [comment]
This issue is really about ROBOT, so I created a new tracker issue in that repository:

https://github.com/ontodev/robot/issues/57
